---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books
  namespace: housekeeping
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: housekeeping-books
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-staging
  namespace: housekeeping
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: housekeeping-books-staging
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: root-ssh
  namespace: housekeeping
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadOnlyMany
  volumeName: housekeeping-root-ssh
  storageClassName: ""

