---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music
  namespace: samba
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadOnlyMany
  volumeName: samba-music
  storageClassName: ""
