apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: samba
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      hostNetwork: true
      initContainers:
      - name: busybox
        image: busybox
        command:
        - cp
        - -aL
        - /samba-src/smbpasswd
        - /samba/
        volumeMounts:
        - name: smbpasswd-src
          mountPath: /samba-src
        - name: smbpasswd
          mountPath: /samba
      containers:
      - name: samba
        image: dperson/samba
        args:
        - -i
        - /samba/smbpasswd
        - -s
        - "music;/srv;yes;yes;no;samba"
        - -g 
        - "ntlm auth = yes" 
        - -S
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi
        ports:
        - containerPort: 139
        - containerPort: 445
        env:
        - name: TZ
          value: Europe/London
        - name: USERID
          value: "1000"
        - name: GROUPID
          value: "1000"
        volumeMounts:
        - name: smbpasswd
          mountPath: /samba
        - name: music
          mountPath: /srv
      volumes:
      - name: smbpasswd-src
        secret:
          secretName: smbpasswd
          defaultMode: 0600
      - name: smbpasswd
        emptyDir:
          medium: Memory
      - name: music
        persistentVolumeClaim:
          claimName: music
          readOnly: true
