apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: health-checker
  namespace: sonarr
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          restartPolicy: Never
          containers:
          - name: health-checker
            image: dippynark/python
            env:
            - name: SONARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sonarr
                  key: sonarr_apikey
            args:
            - bash
            - -c
            - |
              set -euo pipefail

              cat > health-checker.py <<EOF
              import requests
              import json
              import sys
              import os

              url = "http://sonarr.sonarr.svc.cluster.local/api/v3/health"
              r = requests.get(url, headers={"X-Api-Key": os.environ['SONARR_API_KEY']})
              r.raise_for_status()
              json_data = json.loads(r.text)

              unrecognised_error = False
              for error in json_data:
                  source = error["source"]
                  message = error["message"]
                  if source == 'DownloadClientCheck' and message == 'No download client is available':
                      continue
                  if source == 'DownloadClientCheck' and message == 'Unable to communicate with Whatbox. Unable to connect to rTorrent, please check your settings':
                      continue
                  if source == 'DownloadClientStatusCheck' and message == 'All download clients are unavailable due to failures':
                      continue
                  if source == "ImportMechanismCheck" and message == "Enable Completed Download Handling":
                      continue
                  if source == "IndexerStatusCheck" and message == "All indexers are unavailable due to failures":
                      continue
                  if source == "IndexerSearchCheck" and message == "All search-capable indexers are temporarily unavailable due to recent indexer errors":
                      continue
                  if source == "IndexerRssCheck" and message == "All rss-capable indexers are temporarily unavailable due to recent indexer errors":
                      continue
                  if source == "RemovedSeriesCheck" and message == "Series Robot Wars (2016) (tvdbid 314683) was removed from TheTVDB":
                      continue
                  print(error)
                  unrecognised_error = True

              if unrecognised_error == True:
                  sys.exit(1)

              print("Sonarr is healthy")
              EOF
              python health-checker.py
