---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: sonarr
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: sonarr-config
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv-shows
  namespace: sonarr
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: sonarr-tv-shows
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whatbox
  namespace: sonarr
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadOnlyMany
  volumeName: sonarr-whatbox
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: connect
  namespace: sonarr
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: sonarr-connect
  storageClassName: ""
