apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: sonarr
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8989
  selector:
    app: sonarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: sonarr
spec:
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: connect
        image: dippynark/python:v1.0.0
        env:
        - name: WHATBOX_USERNAME
          valueFrom:
            secretKeyRef:
              name: sonarr
              key: whatbox_username
        - name: WHATBOX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarr
              key: whatbox_password
        - name: WHATBOX_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: sonarr
              key: whatbox_hostname
        - name: SONARR_APIKEY
          valueFrom:
            secretKeyRef:
              name: sonarr
              key: sonarr_apikey
        - name: PUSHBULLET_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: sonarr
              key: pushbullet_access_token
        volumeMounts:
        - name: link-script
          mountPath: /opt/bin/link.py
          subPath: link.py
        - name: connect
          mountPath: /connect
        command:
        - sh
        - -c
        - |
          while true; do
            find /connect -type f -exec /opt/bin/link.py $WHATBOX_USERNAME $WHATBOX_PASSWORD $WHATBOX_HOSTNAME $SONARR_APIKEY $PUSHBULLET_ACCESS_TOKEN {} \;
            sleep 10
          done
      - name: sonarr
        image: dippynark/sonarr:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 8989
          name: http
        env:
        - name: TZ
          value: Europe/London
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        livenessProbe:
          httpGet:
            path: /
            port: 8989
          timeoutSeconds: 10
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
        - name: tv-shows
          mountPath: /tv
        - name: config
          mountPath: /config
        - name: whatbox
          mountPath: /mnt/whatbox
        - name: connect
          mountPath: /connect
        - name: connect-script
          mountPath: /opt/bin/connect.sh
          subPath: connect.sh
      volumes:
      - name: tv-shows
        persistentVolumeClaim:
          claimName: tv-shows
      - name: whatbox
        persistentVolumeClaim:
          claimName: whatbox
          readOnly: true
      - name: config
        persistentVolumeClaim:
          claimName: config
      - name: connect
        persistentVolumeClaim:
          claimName: connect
      - name: connect-script
        configMap:
          name: sonarr
          items:
          - key: connect.sh
            path: connect.sh
            mode: 0555
      - name: link-script
        configMap:
          name: sonarr
          items:
          - key: link.py
            path: link.py
            mode: 0555

