apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: sonarr
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8989
  selector:
    app: sonarr
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  name: sonarr
  namespace: sonarr
spec:
  tls:
  - hosts:
    - sonarr.lukeaddison.co.uk
    secretName: sonarr-tls
  rules:
  - host: sonarr.lukeaddison.co.uk
    http:
      paths:
      - backend:
          serviceName: sonarr
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarr
  namespace: sonarr
spec:
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      containers:
      - name: connect
        image: python:3.7
        env:
        - name: WHATBOX_USERNAME
          valueFrom:
            secretKeyRef:
              name: sonarr
              key: whatbox_username
        - name: WHATBOX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarr
              key: whatbox_password
        - name: WHATBOX_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: sonarr
              key: whatbox_hostname
        - name: SONARR_USERNAME
          valueFrom:
            secretKeyRef:
              name: sonarr
              key: sonarr_username
        - name: SONARR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarr
              key: sonarr_password
        - name: SONARR_APIKEY
          valueFrom:
            secretKeyRef:
              name: sonarr
              key: sonarr_apikey
        - name: PUSHBULLET_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: sonarr
              key: pushbullet_access_token
        volumeMounts:
        - name: link-script
          mountPath: /opt/bin/link.py
          subPath: link.py
        - name: connect
          mountPath: /connect
        command:
        - sh
        - -c
        - |
          pip install requests pushbullet.py
          while true; do
            find /connect -type f -exec /opt/bin/link.py $WHATBOX_USERNAME $WHATBOX_PASSWORD $WHATBOX_HOSTNAME $SONARR_USERNAME $SONARR_PASSWORD $SONARR_APIKEY $PUSHBULLET_ACCESS_TOKEN {} \;
            sleep 10
          done
      - name: sonarr
        image: linuxserver/sonarr
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8989
          timeoutSeconds: 30
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 8989
          failureThreshold: 10
          timeoutSeconds: 30
          periodSeconds: 30
          initialDelaySeconds: 180
        ports:
        - containerPort: 8989
          name: http
        env:
        - name: TZ
          value: Europe/London
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - name: tv
          mountPath: /tv
        - name: config
          mountPath: /config
        - name: whatbox
          mountPath: /mnt/whatbox
          readOnly: true
        - name: connect
          mountPath: /connect
        - name: connect-script
          mountPath: /opt/bin/connect.sh
          subPath: connect.sh
      nodeName: core1
      volumes:
      - name: tv
        hostPath:
          path: /mnt/google-drive/Media/TV Shows
      - name: whatbox
        hostPath:
          path: /mnt/whatbox
      - name: config
        hostPath:
          path: /mnt/data/volumes/sonarr
      - name: connect
        persistentVolumeClaim:
          claimName: connect
      - name: connect-script
        configMap:
          name: sonarr
          items:
          - key: connect.sh
            path: connect.sh
            mode: 0555
      - name: link-script
        configMap:
          name: sonarr
          items:
          - key: link.py
            path: link.py
            mode: 0555

