apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway-external
  namespace: istio-system
spec:
  type: NodePort
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  ports:
  - name: http2
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: https-plex
    protocol: TCP
    port: 32400
    nodePort: 32400
