---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tautulli-plex-logs
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadOnlyMany
  local:
    path: /var/lib/kubernetes/volumes/plex-config/Library/Application Support/Plex Media Server/Logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - core1
