---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-logs
  namespace: tautulli
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadOnlyMany
  volumeName: tautulli-plex-logs
  storageClassName: ""
