apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: requests-dippystreams-co-uk-tls
  namespace: istio-system
spec:
  secretName: requests-dippystreams-co-uk-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - requests.dippystreams.co.uk
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ombi
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - requests.dippystreams.co.uk
    tls:
      httpsRedirect: true
  - port:
      number: 8443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: requests-dippystreams-co-uk-tls
    hosts:
    - ombi/requests.dippystreams.co.uk
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ombi
  namespace: ombi
spec:
  hosts:
  - requests.dippystreams.co.uk
  gateways:
  - istio-system/ombi
  http:
  - match:
    - port: 8443
    route:
    - destination:
        host: ombi
