apiVersion: v1
kind: Service
metadata:
  name: ombi
  namespace: ombi
  labels:
    app: ombi
spec:
  selector:
    app: ombi
  ports:
  - port: 80
    targetPort: 3579
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ombi
  namespace: ombi
spec:
  selector:
    matchLabels:
      app: ombi
  template:
    metadata:
      labels:
        app: ombi
    spec:
      containers:
      - name: ombi
        image: linuxserver/ombi:v3.0.4892-ls38
        ports:
        - containerPort: 3579
        env:
        - name: TZ
          value: Europe/London
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        readinessProbe:
          httpGet:
            path: /login
            port: 3579
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /login
            port: 3579
          timeoutSeconds: 10
          initialDelaySeconds: 60
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
