apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: ombi
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: ombi-config
  storageClassName: ""
