---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
  labels:
    app: plex
spec:
  type: NodePort
  selector:
    app: plex
  ports:
  - name: https
    protocol: TCP
    port: 32400
    nodePort: 32400
---
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      priorityClassName: high-priority
      containers:
      - name: plex
        image: plexinc/pms-docker
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0.2
            memory: 1Gi
          limits:
            nvidia.com/gpu: 1
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /identity
            port: 32400
          failureThreshold: 5
          timeoutSeconds: 15
          periodSeconds: 15
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /identity
            port: 32400
          initialDelaySeconds: 120
          failureThreshold: 5
          timeoutSeconds: 15
          periodSeconds: 15
        ports:
        - containerPort: 32400
          name: https
        env:
        - name: TZ
          value: Europe/London
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        # Refresh shared library cache
        lifecycle:
          postStart:
            exec:
              command:
              - /sbin/ldconfig
        volumeMounts:
        - name: music
          mountPath: /data/Music
        - name: tv-shows
          mountPath: /data/TV Shows
        - name: films
          mountPath: /data/Films
        - name: config
          mountPath: /config
        - name: transcode
          mountPath: /transcode
        - name: tmp
          mountPath: /tmp
        - name: ldconfig
          mountPath: /etc/ld.so.conf.d/nvidia.conf
          subPath: nvidia.conf
      volumes:
      - name: music
        persistentVolumeClaim:
          claimName: music
          readOnly: true
      - name: tv-shows
        persistentVolumeClaim:
          claimName: tv-shows
          readOnly: true
      - name: films
        persistentVolumeClaim:
          claimName: films
          readOnly: true
      - name: config
        persistentVolumeClaim:
          claimName: config
      - name: transcode
        emptyDir:
          medium: Memory
      - name: tmp
        emptyDir: {}
      - name: ldconfig
        configMap:
          name: ldconfig
          items:
          - key: nvidia.conf
            path: nvidia.conf
