---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
  labels:
    app: plex
spec:
  type: NodePort
  selector:
    app: plex
  ports:
  - name: http
    protocol: TCP
    port: 32400
    nodePort: 32400
---
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      priorityClassName: high-priority
      containers:
      - name: plex
        image: plexinc/pms-docker:1.17.0.1709-982421575
        resources:
          requests:
            cpu: 0.2
            memory: 1Gi
        readinessProbe:
          exec:
            command:
            - /healthcheck.sh
          failureThreshold: 5
          timeoutSeconds: 15
          periodSeconds: 15
        livenessProbe:
          exec:
            command:
            - /healthcheck.sh
          initialDelaySeconds: 120
          failureThreshold: 5
          timeoutSeconds: 15
          periodSeconds: 15
        ports:
        - containerPort: 32400
          name: http
        env:
        - name: TZ
          value: Europe/London
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - name: music
          mountPath: /data/Music
          readOnly: true
        - name: tv-shows
          mountPath: /data/TV Shows
          readOnly: true
        - name: films
          mountPath: /data/Films
          readOnly: true
        - name: config
          mountPath: /config
        - name: transcode
          mountPath: /transcode
        - name: tmp
          mountPath: /tmp
        - name: google-drive-media
          mountPath: /mnt/google-drive/Media
          readOnly: true
      nodeName: core1
      volumes:
      - name: google-drive-media
        hostPath:
          path: /mnt/google-drive/Media
      - name: music
        hostPath:
          path: /mnt/data/media/Music
      - name: tv-shows
        hostPath:
          path: /mnt/data/plex/TV Shows
      - name: films
        hostPath:
          path: /mnt/data/media/Films
      - name: config
        persistentVolumeClaim:
          claimName: plex
      - name: transcode
        emptyDir: {}
      - name: tmp
        emptyDir: {}
