---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plex
  namespace: plex
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/secure-backends: "true"
spec:
  tls:
  - secretName: plex-tls
    hosts:
    - plex.lukeaddison.co.uk  
  rules:
  - host: plex.lukeaddison.co.uk
    http:
      paths:
      - backend:
          serviceName: plex
          servicePort: 32400
  - host: plex
    http:
      paths:
      - backend:
          serviceName: plex
          servicePort: 32400
  