apiVersion: v1
kind: Namespace
metadata:
  name: filebrowser
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: filebrowser
  labels:
    app: filebrowser
spec:
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:v1.10.0
        command:
        - /filebrowser
        - --config
        - /etc/filebrowser/config.yaml
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /etc/filebrowser
        - name: database
          mountPath: /database
      volumes:
      - name: data
        nfs:
          server: node1.lukeaddison.co.uk
          path: "/mnt/data/plex"
          readOnly: true
      - name: config
        configMap:
          name: filebrowser
      - name: database
        persistentVolumeClaim:
          claimName: filebrowser
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: filebrowser
  labels:
    app: filebrowser
spec:
  selector:
    app: filebrowser
  ports:
  - name: http
    protocol: TCP
    port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: filebrowser
  namespace: filebrowser
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - secretName: filebrowser-tls
    hosts:
    - filebrowser.lukeaddison.co.uk  
  rules:
  - host: filebrowser.lukeaddison.co.uk
    http:
      paths:
      - backend:
          serviceName: filebrowser
          servicePort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser
  namespace: filebrowser
data:
  config.yaml: |
    port: 80
    database: "/database/database.db"
    scope: "/data"
    allowCommands: false
    allowEdit: false
    allowNew: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
