---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bookstack
  namespace: bookstack
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - secretName: bookstack-tls
    hosts:
    - wiki.lukeaddison.co.uk
  rules:
  - host: wiki.lukeaddison.co.uk
    http:
      paths:
      - backend:
          serviceName: bookstack
          servicePort: 80
  - host: wiki
    http:
      paths:
      - backend:
          serviceName: bookstack
          servicePort: 80