---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: bookstack
  labels:
    app: bookstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi