---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: bookstack
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: bookstack-mysql
  storageClassName: ""
