# https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/auth/oauth-external-auth
{{- $root := . }}
{{- range .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy{{ .suffix }}
  name: oauth2-proxy{{ .suffix }}
  namespace: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy{{ .suffix }}
  template:
    metadata:
      labels:
        app: oauth2-proxy{{ .suffix }}
    spec:
      containers:
      - name: oauth2-proxy
        image: {{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}
        args:
        - --provider=google
        - --whitelist-domain=.{{ $root.Values.domain }}
        - --cookie-domain=.{{ $root.Values.domain }}
        - --authenticated-emails-file=/etc/oauth2-proxy/authenticated-emails.txt
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy{{ .suffix }}
              key: OAUTH2_PROXY_CLIENT_ID
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy{{ .suffix }}
              key: OAUTH2_PROXY_CLIENT_SECRET
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy{{ .suffix }}
              key: OAUTH2_PROXY_COOKIE_SECRET
        ports:
        - containerPort: 4180
          protocol: TCP
        readinessProbe:
          periodSeconds: 3
          httpGet:
            path: /ping
            port: 4180
        volumeMounts:
        - name: authenticated-emails
          mountPath: /etc/oauth2-proxy
      volumes:
      - name: authenticated-emails
        secret:
          secretName: oauth2-proxy{{ .suffix }}
          items:
          - key: authenticated-emails.txt
            path: authenticated-emails.txt
{{- end }}
