{{- range .Values.deployments }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy{{ .suffix }}
  namespace: oauth2-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - secretName: oauth2-{{ .suffix }}-tls
    hosts:
    - {{ .hostname }}
  rules:
  - host: {{ .hostname }}
    http:
      paths:
      - path: /oauth2
        backend:
          serviceName: oauth2-proxy{{ .suffix }}
          servicePort: 4180
{{- end }}
