apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  ports:
  - name: http-web
    port: 80
    protocol: TCP
    targetPort: web
  selector:
    app: alertmanager
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  image: quay.io/prometheus/alertmanager:v0.20.0
  externalUrl: https://alertmanager.lukeaddison.co.uk
  listenLocal: false
  portName: http-web
  logFormat: logfmt
  logLevel: info
  paused: false
  retention: 120h
  routePrefix: /
  resources:
    requests:
      memory: 400Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  #serviceAccountName: prometheus-operator-alertmanager
  version: v0.20.0
