---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fluent-bit
  namespace: monitoring
  labels:
    type: platform
spec:
  selector:
    matchLabels:
      app: fluent-bit
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: metrics
    path: /api/v1/metrics/prometheus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit
  namespace: monitoring
  labels:
    app: fluent-bit
data:
  fluent-bit-service.conf: |-
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

  fluent-bit-input.conf: |-
    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
    
    [INPUT]
        Name  systemd
        Tag   host.*

  fluent-bit-filter.conf: |-
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

  fluent-bit-output.conf: |-
    [OUTPUT]
        Name   loki
        Match  *
        Url    http://loki.monitoring.svc.cluster.local:3100/api/prom/push
        Labels {job="fluent-bit", instance="${HOSTNAME}"}

  fluent-bit.conf: |-
    @INCLUDE fluent-bit-service.conf
    @INCLUDE fluent-bit-input.conf
    @INCLUDE fluent-bit-filter.conf
    @INCLUDE fluent-bit-output.conf

  parsers.conf: |-
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: fluent-bit
  name: fluent-bit
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: fluent-bit
  name: fluent-bit
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: fluent-bit
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: monitoring
  labels:
    app: fluent-bit
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - port: 2020
    targetPort: metrics
    name: metrics
  selector:
    app: fluent-bit
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: monitoring
  labels:
    app: fluent-bit
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fluent-bit
        release: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      initContainers:
      - name: install-loki-output-plugin
        image: dippynark/fluent-bit-go-loki
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - |
          cp /loki.so /usr/lib/fluent-bit/loki.so
        volumeMounts:
        - name: usr-lib-fluent-bit
          mountPath: /usr/lib/fluent-bit
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.2.2
        args:
        - /fluent-bit/bin/fluent-bit
        - -c
        - /fluent-bit/etc/fluent-bit.conf
        - -e
        - /usr/lib/fluent-bit/loki.so
        ports:
        - name: metrics
          containerPort: 2020
          protocol: TCP
        volumeMounts:
        - name: var-log
          mountPath: /var/log
        - name: var-lib-docker-containers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit-service.conf
          subPath: fluent-bit-service.conf
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit-input.conf
          subPath: fluent-bit-input.conf
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit-filter.conf
          subPath: fluent-bit-filter.conf
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit-output.conf
          subPath: fluent-bit-output.conf
        - name: usr-lib-fluent-bit
          mountPath: /usr/lib/fluent-bit
      volumes:
      - name: var-log
        hostPath:
          path: /var/log
      - name: var-lib-docker-containers
        hostPath:
          path: /var/lib/docker/containers      
      - name: config
        configMap:
          name: fluent-bit
      - name: usr-lib-fluent-bit
        emptyDir: {}
