apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kubeadm-cert-checker
  namespace: monitoring
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          restartPolicy: Never
          containers:
          - name: kubeadm-cert-checker
            image: dippynark/kubeadm:v1.16.2
            volumeMounts:
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
            command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail

              RESIDUAL_TIMES=$(kubeadm alpha certs check-expiration | tail -n +2 | awk '{print $7}' | tr '\n' ' ')
              for RESIDUAL_TIME in $RESIDUAL_TIMES; do
                if [ $(echo $RESIDUAL_TIME | sed 's/d//') -gt 90 ]; then
                  :
                else
                  exit 1
                fi
              done
              echo Success!
          volumes:
          - name: etc-kubernetes
            persistentVolumeClaim:
              claimName: etc-kubernetes
              readOnly: true
