---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-etc-kubernetes
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadOnlyMany
  local:
    path: /etc/kubernetes
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - core1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-kubernetes
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadOnlyMany
  volumeName: monitoring-etc-kubernetes
  storageClassName: ""
