apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redistimeseries
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: monitoring-redistimeseries
  storageClassName: ""
