apiVersion: v1
kind: Service
metadata:
  name: redistimeseries
  namespace: monitoring
spec:
  ports:
  - port: 6379
    name: redis
    targetPort: redis
  selector:
    app: redistimeseries
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redistimeseries
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: redistimeseries
  serviceName: redistimeseries
  replicas: 1
  template:
    metadata:
      labels:
        app: redistimeseries
    spec:
      containers:
      - name: redis
        image: redislabs/redistimeseries:1.4.2
        args:
        - --requirepass
        - $(REDIS_PASS)
        - --appendonly
        - "yes"
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redistimeseries
              key: REDIS_PASS
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redistimeseries
