apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: monitoring-redis
  storageClassName: ""
