apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: whatbox-disk-space-checker
  namespace: monitoring
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: whatbox-disk-space-checker
            image: python:3
            env:
            - name: WHATBOX_USERNAME
              valueFrom:
                secretKeyRef:
                  name: whatbox
                  key: username
            - name: WHATBOX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: whatbox
                  key: password
            - name: WHATBOX_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: whatbox
                  key: hostname
            args:
            - bash
            - -c
            - |
              set -euo pipefail

              pip install requests
              cat > whatbox-disk-space-checker.py <<'EOF'
              import requests
              import os
              import sys
              import json
              import xmlrpc.client

              server_url = "https://%s:%s@%s/xmlrpc" % (os.environ['WHATBOX_USERNAME'], os.environ['WHATBOX_PASSWORD'], os.environ['WHATBOX_HOSTNAME']);
              server = xmlrpc.client.Server(server_url);

              s = requests.Session() 
              r = s.post("https://%s/login" % os.environ['WHATBOX_HOSTNAME'], data={'username': os.environ['WHATBOX_USERNAME'], 'password': os.environ['WHATBOX_PASSWORD']})
              r = s.get("https://%s/api/disk_usage" % os.environ['WHATBOX_HOSTNAME'])

              json_response = json.loads(r.text)
              disk_space_allotted = json_response['disk_space_allotted']
              disk_space_used = json_response['disk_space_used']
              if disk_space_used/disk_space_allotted > 0.95:
                  print("ERROR: disk space usage is over 95%")

                  # pause all incomplete torrents
                  server.d.multicall.filtered("",
                    "main",
                    "and=\"d.incomplete=,cat=1\",\"or=\\\"equal=d.custom1=,cat=LukeBooks\\\",\\\"equal=d.custom1=,cat=LukeFilms\\\",\\\"equal=d.custom1=,cat=LukeMusic\\\",\\\"equal=d.custom1=,cat=LukeTVShows\\\",\\\"equal=d.custom1=,cat=LukeApplications\\\",\\\"equal=d.custom1=,cat=LukeGames\\\"\"",
                    "d.pause=")

                  sys.exit(1)
              elif disk_space_used/disk_space_allotted <= 0.90:
                  # resume all incomplete torrents
                  server.d.multicall.filtered("",
                    "main",
                    "and=\"d.incomplete=,cat=1\",\"or=\\\"equal=d.custom1=,cat=LukeBooks\\\",\\\"equal=d.custom1=,cat=LukeFilms\\\",\\\"equal=d.custom1=,cat=LukeMusic\\\",\\\"equal=d.custom1=,cat=LukeTVShows\\\",\\\"equal=d.custom1=,cat=LukeApplications\\\",\\\"equal=d.custom1=,cat=LukeGames\\\"\"",
                    "d.resume=")
              EOF
              python whatbox-disk-space-checker.py
