apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: whatbox-torrent-status-checker
  namespace: monitoring
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: whatbox-torrent-status-checker
            image: dippynark/python
            env:
            - name: WHATBOX_USERNAME
              valueFrom:
                secretKeyRef:
                  name: whatbox
                  key: username
            - name: WHATBOX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: whatbox
                  key: password
            - name: WHATBOX_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: whatbox
                  key: hostname
            - name: TRACKER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: tracker
                  key: email
            - name: TRACKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tracker
                  key: password
            - name: TRACKER_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: tracker
                  key: hostname
            - name: TRACKER_ID
              valueFrom:
                secretKeyRef:
                  name: tracker
                  key: id
            args:
            - bash
            - -c
            - |
              set -euo pipefail

              cat > whatbox-torrent-status-checker.py <<EOF
              import datetime
              import os
              import sys
              import xmlrpc.client
              import mechanicalsoup

              current_time = datetime.datetime.now().time()
              if current_time < datetime.time(10) or datetime.time(22) < current_time:
                  sys.exit(0)

              server_url = "https://%s:%s@%s/xmlrpc" % (os.environ['WHATBOX_USERNAME'], os.environ['WHATBOX_PASSWORD'], os.environ['WHATBOX_HOSTNAME']);
              server = xmlrpc.client.Server(server_url);

              torrents = server.d.multicall.filtered("",
                  "main",
                  "or=\"equal=d.custom1=,cat=LukeBooks\",\"equal=d.custom1=,cat=LukeFilms\",\"equal=d.custom1=,cat=LukeMusic\",\"equal=d.custom1=,cat=LukeTVShows\",\"equal=d.custom1=,cat=LukeApplications\",\"equal=d.custom1=,cat=LukeGames\"",
                  "d.name=",
                  "d.hash=",
                  "d.state=",
                  "d.is_open=",
                  "d.is_active=",
                  "d.message=")

              irrecoverable_errors = False
              for torrent in torrents:
                  name = torrent[0]
                  hash = torrent[1]
                  state = torrent[2]
                  is_open = torrent[3]
                  is_active = torrent[4]
                  message = torrent[5]
                  if state != 1 or is_open != 1 or is_active != 1 or message != "":

                      if message.startswith('Tracker: [') and message.endswith(']'):
                          tracker_message = message[len('Tracker: ['):len(message) - len(']')]

                          if tracker_message == 'Timed out':
                              continue
                          if tracker_message == "Couldn't connect to server":
                              continue
                          if tracker_message == "Timeout was reached":
                              continue
                          if tracker_message == "Could not parse bencoded data: 504 Gateway Time-out    504 Gateway Time-out  nginx":
                              continue
                          if tracker_message == "Could not parse bencoded data: 502 Bad Gateway    502 Bad Gateway  nginx":
                              continue
                          if tracker_message == "SSL connect error":
                              continue
                          if tracker_message == "Server returned nothing (no headers, no data)":
                              continue

                          if tracker_message.startswith('Failure reason "') and tracker_message.endswith('"'):
                              tracker_failure_reason = tracker_message[len('Failure reason "'):len(tracker_message) - len('"')]

                              if tracker_failure_reason == "The tracker is down. We\'re working on fixing the problem":
                                  continue

                              if tracker_failure_reason == 'Unregistered torrent':
                                  print("Erasing %s: %s" % (name, tracker_failure_reason))
                                  server.d.erase(hash)
                                  continue

                              if tracker_failure_reason == "Not VIP":
                                  login_url = "https:/%s/login.php" % os.environ['TRACKER_HOSTNAME']
                                  user_url = "https://%s/u/%s" % (os.environ['TRACKER_HOSTNAME'], os.environ['TRACKER_ID'])
                                  vip_buy_url = "https://%s/json/bonusBuy.php?spendtype=VIP&duration=4" % os.environ['TRACKER_HOSTNAME']

                                  browser = mechanicalsoup.StatefulBrowser()
                                  browser.open(login_url)

                                  browser.select_form('form[action="/takelogin.php"]')
                                  browser["email"] = os.environ['TRACKER_EMAIL']
                                  browser["password"] = os.environ['TRACKER_PASSWORD']
                                  r = browser.submit_selected()
                                  r.raise_for_status()

                                  r = browser.get(user_url)
                                  r.raise_for_status()

                                  rows = list(browser.get_current_page().find_all('tr'))
                                  vip_enabled = False
                                  for row in rows:
                                      row_title = row.find('td', class_='rowhead').text
                                      if row_title == 'Class':
                                          class_name = row.find('td', class_='row1').text
                                          if class_name != "VIP":
                                              if class_name == "Power User":
                                                  r = browser.get(vip_buy_url)
                                                  r.raise_for_status()
                                                  vip_enabled = True
                                              else:
                                                  print("ERROR: unexpected class: %s" % class_name)
                                          else:
                                              vip_enabled = True
                                          break
                                  if vip_enabled:
                                      continue

                      irrecoverable_errors = True
                      print("Name: %s, Message: %s" % (name, message))

              if irrecoverable_errors:
                  sys.exit(1)
              EOF
              python whatbox-torrent-status-checker.py
