apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: whatbox-torrent-status-checker
  namespace: monitoring
spec:
  schedule: "0 14 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: whatbox-torrent-status-checker
            image: python:3
            env:
            - name: WHATBOX_USERNAME
              valueFrom:
                secretKeyRef:
                  name: whatbox
                  key: username
            - name: WHATBOX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: whatbox
                  key: password
            - name: WHATBOX_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: whatbox
                  key: hostname
            args:
            - bash
            - -c
            - |
              set -euo pipefail

              cat > whatbox-torrent-status-checker.py <<EOF
              import os
              import sys
              import xmlrpc.client

              server_url = "https://%s:%s@%s/xmlrpc" % (os.environ['WHATBOX_USERNAME'], os.environ['WHATBOX_PASSWORD'], os.environ['WHATBOX_HOSTNAME']);
              server = xmlrpc.client.Server(server_url);

              torrents = server.d.multicall.filtered("",
                  "main",
                  "or=\"equal=d.custom1=,cat=LukeBooks\",\"equal=d.custom1=,cat=LukeFilms\",\"equal=d.custom1=,cat=LukeMusic\",\"equal=d.custom1=,cat=LukeTVShows\",\"equal=d.custom1=,cat=LukeApplications\"",
                  "d.name=",
                  "d.state=",
                  "d.is_open=",
                  "d.is_active=",
                  "d.message=")

              for torrent in torrents:
                  name = torrent[0]
                  state = torrent[1]
                  is_open = torrent[2]
                  is_active = torrent[3]
                  message = torrent[4]
                  if state != 1 or is_open != 1 or is_active != 1 or message != "":
                      print("ERROR: %s %s %s %s %s" % (name, state, is_open, is_active, message))
                      sys.exit(1)
              EOF
              python whatbox-torrent-status-checker.py
