---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-whatbox-luke
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  local:
    path: /mnt/whatbox/luke
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - core1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whatbox-luke
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: monitoring-whatbox-luke
  storageClassName: ""
