server:
  service:
    type: ClusterIP
  ingress:
    hosts:
    - gocd.lukeaddison.co.uk
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-url: "https://oauth2.lukeaddison.co.uk/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.lukeaddison.co.uk/oauth2/start?rd=https://$host$request_uri"
    tls:
    - hosts:
      - gocd.lukeaddison.co.uk
      secretName: gocd-tls
