apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prune
  namespace: docker
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: prune
  template:
    metadata:
      labels:
        app: prune
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - image: docker:19.03.13
        name: prune
        command:
        - sh
        - -c
        - |
          apk add --update jq

          while true; do
            # Cannot use system or container prune as this triggers Kubernetes to restart init
            # containers
            # https://github.com/kubernetes/kubernetes/issues/86531
            #docker system prune -f --filter "until=48h"
            #docker container prune -f --filter "until=48h"

            # Cannot use image prune since that only looks at when the image was last created (instead of used)
            # docker image prune -af --filter "until=48h"

            # https://github.com/moby/moby/issues/9054#issuecomment-227920187
            docker images | grep -v REPOSITORY | awk '{print $3}' | xargs -n 1 docker history | grep -v missing | grep -v "^IMAGE" | egrep -v "day|hour|minute|second" | awk '{print $1}' | sort | uniq | xargs -n 1 docker inspect | jq -r '.[0].RepoTags[]' | sort > old-images.txt
            docker images | grep -v REPOSITORY | awk '{print $3}' | xargs -n 1 docker history | grep -v missing | grep -v "^IMAGE" | egrep "day|hour|minute|second" | awk '{print $1}' | sort | uniq | xargs -n 1 docker inspect | jq -r '.[0].RepoTags[]' | sort > new-images.txt
            # https://stackoverflow.com/a/4366568
            comm -23 new-images.txt old-images.txt | xargs docker rmi 2>/dev/null

            # Remove all unused local volumes
            docker volume prune -f

            # Sleep for a day
            sleep $(( 24 * 60 * 60 ))
          done
        env:
        - name: DOCKER_API_VERSION
          value: "1.38"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /var/lib/docker
          name: docker-directory
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: docker-directory
        hostPath:
          path: /var/lib/docker
