apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prune
  namespace: docker
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: prune
  template:
    metadata:
      labels:
        app: prune
    spec:
      containers:
      - image: docker:stable
        name: prune
        command:
        - sh
        - -c
        - |
          while true; do
            #docker system prune -f --filter "until=48h"
            #docker container prune -f --filter "until=48h"
            # Cannot use system or conntainer prune as this triggers Kubernetes to restart init
            # containers
            # https://github.com/kubernetes/kubernetes/issues/86531
            docker image prune -af --filter "until=48h"

            docker volume prune -f
            sleep 3600
          done
        env:
        - name: DOCKER_API_VERSION
          value: "1.38"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /var/lib/docker
          name: docker-directory
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: docker-directory
        hostPath:
          path: /var/lib/docker
