apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: health-checker
  namespace: radarr
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          restartPolicy: Never
          containers:
          - name: health-checker
            image: dippynark/python
            env:
            - name: RADARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: radarr
                  key: radarr_apikey
            args:
            - bash
            - -c
            - |
              set -euo pipefail

              cat > health-checker.py <<EOF
              import requests
              import json
              import sys
              import os

              url = "http://radarr.radarr.svc.cluster.local/api/health"
              r = requests.get(url, headers={"X-Api-Key": os.environ['RADARR_API_KEY']})
              r.raise_for_status()
              json_data = json.loads(r.text)

              unrecognised_error = False
              for error in json_data:
                  if error["message"] == 'No download client is available':
                      continue
                  if error["message"] == 'Unable to communicate with Whatbox. Gateway Time-out':
                      continue
                  print(error)
                  unrecognised_error = True

              if unrecognised_error == True:
                  sys.exit(1)

              print("Radarr is healthy")
              EOF
              python health-checker.py
