---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: radarr
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: radarr-config
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: films
  namespace: radarr
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: radarr-films
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whatbox
  namespace: radarr
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadOnlyMany
  volumeName: radarr-whatbox
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: connect
  namespace: radarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
