# Source: kiali-server/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali
  namespace: kiali
  labels:
    helm.sh/chart: kiali-server-1.25.0
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
    version: "v1.25.0"
    app.kubernetes.io/version: "v1.25.0"
    app.kubernetes.io/managed-by: Helm
