# Source: Istio/templates/istioctl.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: istio-ingressgateway-internal
  namespace: istio-system
  labels:
    app: istio-ingressgateway-internal
    istio: ingressgateway
    release: istio
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-ingressgateway-internal
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
