# Source: Istio/templates/istioctl.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kiali
    release: istio
  name: kiali
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiali
  template:
    metadata:
      annotations:
        kiali.io/runtimes: go,kiali
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "true"
      labels:
        app: kiali
        release: istio
      name: kiali
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
              weight: 2
            - preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - ppc64le
              weight: 2
            - preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - s390x
              weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
        - command:
            - /opt/kiali/kiali
            - -config
            - /kiali-configuration/config.yaml
            - -v
            - "3"
          env:
            - name: ACTIVE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/kiali/kiali:v1.22
          livenessProbe:
            httpGet:
              path: //healthz
              port: 20001
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
          name: kiali
          readinessProbe:
            httpGet:
              path: //healthz
              port: 20001
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
          resources:
            requests:
              cpu: 10m
          volumeMounts:
            - mountPath: /kiali-configuration
              name: kiali-configuration
            - mountPath: /kiali-cert
              name: kiali-cert
            - mountPath: /kiali-secret
              name: kiali-secret
      serviceAccountName: kiali-service-account
      volumes:
        - configMap:
            name: kiali
          name: kiali-configuration
        - name: kiali-cert
          secret:
            optional: true
            secretName: istio.kiali-service-account
        - name: kiali-secret
          secret:
            optional: true
            secretName: kiali
