apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: jackett
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9117
  selector:
    app: jackett
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: jackett
spec:
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jackett
        image: linuxserver/jackett
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        readinessProbe:
          httpGet:
            path: /UI/Login
            port: 9117
          timeoutSeconds: 15
          periodSeconds: 15
        ports:
        - containerPort: 9117
          name: http
        env:
        - name: TZ
          value: Europe/London
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: blackhole
          mountPath: /downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
      - name: blackhole
        emptyDir: {}
