apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-config
  namespace: calibre
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: calibre-web-config
  storageClassName: ""