apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: www.goodreads.com
  namespace: calibre
spec:
  hosts:
  - www.goodreads.com
  exportTo:
  - "."
  resolution: DNS
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: smtp.gmail.com
  namespace: calibre
spec:
  hosts:
  - smtp.gmail.com
  exportTo:
  - "."
  resolution: DNS
  location: MESH_EXTERNAL
  ports:
  - number: 587
    name: tcp
    protocol: TCP
