apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress
  namespace: wordpress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-url: "https://oauth2.wordpress.lukeaddison.co.uk/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.wordpress.lukeaddison.co.uk/oauth2/start?rd=https://$host$request_uri"
spec:
  tls:
  - secretName: wordpress-tls
    hosts:
    - wordpress.lukeaddison.co.uk
  rules:
  - host: wordpress.lukeaddison.co.uk
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 80
