# Danny
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: danny-wordpress
  namespace: wordpress
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: wordpress-danny-wordpress
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: danny-mariadb
  namespace: wordpress
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: wordpress-danny-mariadb
  storageClassName: ""
