apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway-internal
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway-internal
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    # TODO: enable mTLS
    #tls:
    #  mode: ISTIO_MUTUAL
    hosts:
    - monitoring/prometheus.lukeaddison.co.uk
