apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway-internal
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway-internal
  servers:
  - port:
      number: 8080
      name: https
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL
    hosts:
    - monitoring/prometheus.lukeaddison.co.uk
    - monitoring/alertmanager.lukeaddison.co.uk
    - monitoring/grafana.lukeaddison.co.uk
    - jackett/jackett.lukeaddison.co.uk
    - bookstack/wiki.lukeaddison.co.uk
    - lazylibrarian/lazylibrarian.lukeaddison.co.uk
    - kiali/kiali.lukeaddison.co.uk
    - radarr/radarr.lukeaddison.co.uk
    - sonarr/sonarr.lukeaddison.co.uk
    - lidarr/lidarr.lukeaddison.co.uk
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-ingressgateway-internal
  namespace: istio-system
spec:
  host: istio-ingressgateway-internal.istio-system.svc.cluster.local
  subsets:
  - name: prometheus
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: prometheus.lukeaddison.co.uk
  - name: alertmanager
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: alertmanager.lukeaddison.co.uk
  - name: grafana
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: grafana.lukeaddison.co.uk
  - name: jackett
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: jackett.lukeaddison.co.uk
  - name: bookstack
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: wiki.lukeaddison.co.uk
  - name: lazylibrarian
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: lazylibrarian.lukeaddison.co.uk
  - name: kiali
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: kiali.lukeaddison.co.uk
  - name: radarr
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: radarr.lukeaddison.co.uk
  - name: sonarr
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: sonarr.lukeaddison.co.uk
  - name: lidarr
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: lidarr.lukeaddison.co.uk
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-ingressgateway-internal
  namespace: istio-system
spec:
  hosts:
  - prometheus.lukeaddison.co.uk
  - alertmanager.lukeaddison.co.uk
  - grafana.lukeaddison.co.uk
  - jackett.lukeaddison.co.uk
  - wiki.lukeaddison.co.uk
  - lazylibrarian.lukeaddison.co.uk
  - kiali.lukeaddison.co.uk
  - radarr.lukeaddison.co.uk
  - sonarr.lukeaddison.co.uk
  - lidarr.lukeaddison.co.uk
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - match:
    - port: 8443
    route:
    - destination:
        host: istio-ingressgateway-internal
        subset: prometheus
        port:
          number: 80
  - match:
    - port: 8443
    route:
    - destination:
        host: istio-ingressgateway-internal
        subset: alertmanager
        port:
          number: 80
  - match:
    - port: 8443
    route:
    - destination:
        host: istio-ingressgateway-internal
        subset: grafana
        port:
          number: 80
  - match:
    - port: 8443
    route:
    - destination:
        host: istio-ingressgateway-internal
        subset: jackett
        port:
          number: 80
  - match:
    - port: 8443
    route:
    - destination:
        host: istio-ingressgateway-internal
        subset: bookstack
        port:
          number: 80
  - match:
    - port: 8443
    route:
    - destination:
        host: istio-ingressgateway-internal
        subset: lazylibrarian
        port:
          number: 80
  - match:
    - port: 8443
    route:
    - destination:
        host: istio-ingressgateway-internal
        subset: kiali
        port:
          number: 80
  - match:
    - port: 8443
    route:
    - destination:
        host: istio-ingressgateway-internal
        subset: radarr
        port:
          number: 80
  - match:
    - port: 8443
    route:
    - destination:
        host: istio-ingressgateway-internal
        subset: sonarr
        port:
          number: 80
  - match:
    - port: 8443
    route:
    - destination:
        host: istio-ingressgateway-internal
        subset: lidarr
        port:
          number: 80
