apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway-internal
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway-internal
  servers:
  - port:
      number: 8080
      name: https
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL
    hosts:
    - monitoring/prometheus.lukeaddison.co.uk
    - radarr/radarr.lukeaddison.co.uk
    - sonarr/sonarr.lukeaddison.co.uk
    - lidarr/lidarr.lukeaddison.co.uk
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-ingressgateway-internal
  namespace: istio-system
spec:
  host: istio-ingressgateway-internal.istio-system.svc.cluster.local
  subsets:
  - name: prometheus
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: prometheus.lukeaddison.co.uk
  - name: radarr
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: radarr.lukeaddison.co.uk
  - name: sonarr
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: sonarr.lukeaddison.co.uk
  - name: lidarr
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: lidarr.lukeaddison.co.uk
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus
  namespace: istio-system
spec:
  hosts:
  - prometheus.lukeaddison.co.uk
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - match:
    - port: 8443
    route:
    - destination:
        host: istio-ingressgateway-internal
        subset: prometheus
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: radarr
  namespace: istio-system
spec:
  hosts:
  - radarr.lukeaddison.co.uk
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - match:
    - port: 8443
    route:
    - destination:
        host: istio-ingressgateway-internal
        subset: radarr
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sonarr
  namespace: istio-system
spec:
  hosts:
  - sonarr.lukeaddison.co.uk
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - match:
    - port: 8443
    route:
    - destination:
        host: istio-ingressgateway-internal
        subset: sonarr
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lidarr
  namespace: istio-system
spec:
  hosts:
  - lidarr.lukeaddison.co.uk
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - match:
    - port: 8443
    route:
    - destination:
        host: istio-ingressgateway-internal
        subset: lidarr
        port:
          number: 80
