apiVersion: v1
data:
  config.yaml: |
    istio_component_namespaces:
      grafana: istio-system
      tracing: istio-system
      istiod: istio-system
      prometheus: istio-system
    istio_namespace: istio-system
    auth:
      strategy: login
    deployment:
      accessible_namespaces: ['**']
    login_token:
      signing_key: "OqHRj3Hw8l"
    server:
      port: 20001
      web_root: /kiali
    external_services:
      istio:
        url_service_version: http://istiod.istio-system:15014/version
      tracing:
        url:
        in_cluster_url: http://tracing/jaeger
      grafana:
        url:
        in_cluster_url: http://grafana:3000
      prometheus:
        url: http://prometheus.monitoring:9090
kind: ConfigMap
metadata:
  labels:
    app: kiali
    install.operator.istio.io/owning-resource: installed-state
    operator.istio.io/component: AddonComponents
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.0
    release: istio
  name: kiali
  namespace: istio-system
