apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  addonComponents:
    prometheus:
      enabled: false
  components:
    ingressGateways:
    - enabled: false
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
    meshConfig:
      accessLogFile: /dev/stdout
      outboundTrafficPolicy:
        mode: REGISTRY_ONLY
    sidecarInjectorWebhook:
      #enableNamespacesByDefault: true
      rewriteAppHTTPProbe: true
