apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  addonComponents:
    prometheus:
      enabled: false
    kiali:
      enabled: true
  components:
    pilot:
      k8s:
        overlays:
        - apiVersion: policy/v1beta1
          kind: PodDisruptionBudget
          name: istiod
          patches:
          - path: spec.minAvailable
        podDisruptionBudget:
          maxUnavailable: 1
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
    sidecarInjectorWebhook:
      #enableNamespacesByDefault: true
      rewriteAppHTTPProbe: true
