---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static
  namespace: lukeaddison
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: lukeaddison
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: lukeaddison-postgres
  storageClassName: ""
