replicaCount: 2
image:
  repository: dippynark/openvpn-docker
  tag: 1.0.0
service:
  type: NodePort
  nodePort: 31194
resources:
  requests:
    cpu: 100m
    memory: 64Mi
persistence:
  enabled: false
openvpn:
  # Protocol used by openvpn (tcp or udp)
  OVPN_PROTO: udp
  # Kubernetes pod network
  OVPN_K8S_POD_NETWORK: "10.100.0.0"
  # Kubernetes pod network subnet
  OVPN_K8S_POD_SUBNET: "255.255.0.0"
  # Kubernetes service network
  OVPN_K8S_SVC_NETWORK: "10.3.0.0"
  # Kubernetes service network subnet
  OVPN_K8S_SVC_SUBNET: "255.255.0.0"
  # Server certificate data
  keystoreSecret: openvpn
  # Push a `dhcp-option DOMAIN` config
  dhcpOptionDomain: true
  # Use/generate certificate revocation list
  useCrl: false
  # Use/generate a ta.key
  taKey: true
  # Override default cipher
  cipher: AES-256-CBC
  # Arbitrary lines appended to the end of the server configuration file
  conf: |-
    client-to-client
    explicit-exit-notify
    push "redirect-gateway def1"
    push "dhcp-option DOMAIN lukeaddison.co.uk"
