apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: lidarr
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8686
  selector:
    app: lidarr
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  name: lidarr
  namespace: lidarr
spec:
  tls:
  - hosts:
    - lidarr.lukeaddison.co.uk
    secretName: lidarr-tls
  rules:
  - host: lidarr.lukeaddison.co.uk
    http:
      paths:
      - backend:
          serviceName: lidarr
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lidarr
  namespace: lidarr
spec:
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
      - name: lidarr
        image: linuxserver/lidarr
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8686
          timeoutSeconds: 30
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 8686
          failureThreshold: 10
          timeoutSeconds: 30
          periodSeconds: 30
          initialDelaySeconds: 180
        ports:
        - containerPort: 8686
          name: http
        env:
        - name: TZ
          value: Europe/London
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - name: music
          mountPath: /music
        - name: config
          mountPath: /config
        - name: whatbox
          mountPath: /mnt/whatbox
          readOnly: true
      nodeName: core1
      volumes:
      - name: whatbox
        hostPath:
          path: /mnt/whatbox
      - name: music
        hostPath:
          path: /mnt/data/media/Music
      - name: config
        hostPath:
          path: /mnt/data/volumes/lidarr
