---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  local:
    path: /var/lib/kubernetes/volumes/lidarr-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - core1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-music
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  local:
    path: /mnt/data/media/Music
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - core1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-whatbox
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadOnlyMany
  local:
    path: /mnt/whatbox
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - core1
