apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: queue-checker
  namespace: lidarr
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          restartPolicy: Never
          containers:
          - name: queue-checker
            image: dippynark/python:v1.0.0
            env:
            - name: X_API_KEY
              valueFrom:
                secretKeyRef:
                  name: x-api-key
                  key: value
            command:
              - bash
              - -c
              - |
                set -euo pipefail
  
                cat > queue-checker.py <<'EOF'
                import os
                import sys
                import json
                import requests

                unknown_warning = False
                for page in range(1, 1000):

                    url = "http://lidarr.lidarr.svc.cluster.local/api/v1/queue?pageSize=100&page=%s" % str(page)
                    r = requests.get(url, headers={"X-Api-Key": os.environ['X_API_KEY']})
                    r.raise_for_status()
                    json_data = r.json()

                    if page != json_data["page"]:
                        # we have cycled through all the items
                        break

                    record_ids_to_delete = []
                    for record in json_data['records']:
                        # This key does no exist when the download client is unavailable
                        if "trackedDownloadStatus" in record and record['trackedDownloadStatus'] != "Ok":
                            known_reason = False
                            unknown_reason = False
                            for statusMessage in record["statusMessages"]:
                                for message in statusMessage["messages"]:
                                    if message == "Not an upgrade for existing track file(s)" \
                                      or message == "Failed to import track, Destination already exists." \
                                      or message == "Has the same filesize as existing file" \
                                      or message == "Has fewer tracks than existing release":
                                        known_reason = True
                                        continue
                                    if message.startswith("No files found are eligible for import in ") \
                                      or message.startswith("Couldn't find similar album for ") \
                                      or message.startswith("Worst track match: ") \
                                      or message.startswith("Album match is not close enough: ") \
                                      or message == "Has missing tracks" \
                                      or message == "Has unmatched tracks":
                                        known_reason = True
                                        if record['id'] not in record_ids_to_delete:
                                            record_ids_to_delete.append(record['id'])
                                        continue
                                    unknown_reason = True
                                    print("%s: %s" % (statusMessage["title"], message))
                            if unknown_reason or not known_reason:
                                unknown_warning = True
                else:
                    print("ERROR: did not page through all items")
                    sys.exit(1)

                for record_id in record_ids_to_delete:
                    print("Deleting %s" % str(record_id))
                    url = "http://lidarr.lidarr.svc.cluster.local/api/v1/queue"
                    r = requests.delete(url+"/"+str(record_id)+"?blacklist=true&skipredownload=false", headers={"X-Api-Key": os.environ['X_API_KEY']})
                    r.raise_for_status()

                if unknown_warning:
                    print("ERROR: there are unknown warnings")
                    sys.exit(1)

                print("Queue Ok - Nothing to do")
                EOF
                python queue-checker.py
