apiVersion: v1
kind: Service
metadata:
  name: lazylibrarian
  namespace: lazylibrarian
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5299
  selector:
    app: lazylibrarian
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lazylibrarian
  namespace: lazylibrarian
spec:
  selector:
    matchLabels:
      app: lazylibrarian
  template:
    metadata:
      labels:
        app: lazylibrarian
    spec:
      containers:
      - name: lazylibrarian
        image: linuxserver/lazylibrarian
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 5299
          timeoutSeconds: 15
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: 5299
          failureThreshold: 3
          timeoutSeconds: 15
          periodSeconds: 15
          initialDelaySeconds: 300
        ports:
        - containerPort: 5299
          name: http
        env:
        - name: TZ
          value: Europe/London
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: DOCKER_MODS
          value: linuxserver/calibre-web:calibre
        volumeMounts:
        - name: books
          mountPath: /books
        - name: config
          mountPath: /config
      volumes:
      - name: books
        hostPath:
          path: /mnt/data/media/Books
      - name: config
        persistentVolumeClaim:
          claimName: config
