---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: lazylibrarian
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeName: lazylibrarian-config
  storageClassName: ""
