apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: lazylibrarian-gitlab-io
  namespace: lazylibrarian
spec:
  hosts:
  - lazylibrarian.gitlab.io
  exportTo:
  - "."
  resolution: DNS
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: www-goodreads-com
  namespace: lazylibrarian
spec:
  hosts:
  - www.goodreads.com
  exportTo:
  - "."
  resolution: DNS
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
