apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lazylibrarian
  namespace: lazylibrarian
spec:
  hosts:
  - lazylibrarian.lukeaddison.co.uk
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - match:
    - port: 8443
    route:
    - destination:
        host: lazylibrarian
