apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: api-cloudflare-com
  namespace: ddns
spec:
  hosts:
  - api.cloudflare.com
  exportTo:
  - "."
  resolution: DNS
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: https
